# Site settings
title: Robosoft 2022 workshop: Soft Robotics modeling: what are we missing?
author: 
  name: Gianmarco Mengaldo
  email: mpegim@nus.edu.nus
description: "website for robosoft 2022 workshop on soft robotics modeling"

# Build settings
remote_theme: jekyll/minima
