# Site settings
title: Robosoft 2022 workshop: Soft Robotics modeling: what are we missing?
author: 
  name: C Laschi, G Mengaldo, F Renda
description: "website for robosoft 2022 workshop on soft robotics modeling"

# Build settings
theme: jekyll-theme-cayman
