# Site settings
title: 
title-icon: 
description: "Robosoft 2022 workshop: Soft Robotics modeling: what are we missing?"
keywords: "soft robotics, modeling, robosoft, computational physics"
featured-image: 

# author settings for cc-by, appears in the footer and credits
author: robosoft-modeling
pub_year: 2022
github_username: robosoft-modeling
repo: "https://github.com/robosoft-modeling/robosoft-2022-workshop/"

# add search box to footer?
search: true

# add google analytics if desired (optional)
# if blank, it will be ignored
# use JEKYLL_ENV=production on build command
google_analytics: 

# defaults (to simplify front matter)
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
      
# Build settings
markdown: kramdown
# theme: jekyll-theme-cayman
